export const TEXTS = {
   common: {
      tags: "תגיות",
      sizes: "מידות",
      preview: "תצוגה מקדימה",
      pictures: "תמונות",
      save: "שמירה",
      price: "מחיר",
      askAboutDress: "פרטים על השמלה",
      shareBtn: "שתפי שמלה",
      shareTitle: "קלטי איזו שמלה מושלמת!",
   },
   routesTitles: {
      home: "בית",
      about: "אודותיי",
      catalog: "קטלוג שמלות",
      guide: "מדריך",
      newDress: "הוספת שמלה",
   },
   newDress: {
      dressTitle: "כותרת שמלה",
      missingFields: "חסרים שדות",
   },
   askAboutDress: "היי, בנוגע לשמלה הזאת - ",
   modalConfirm: {
      cancel: "ביטול",
      confirmBtn: "אישור",
      yes: "כן",
   },
   messages: {
      delete: "למחוק את - ",
   },
   tags: [
      "מחוך",
      "טול",
      "מקסי",
      "מידי",
      "סאטן",
      "תחרה",
      "שחור",
      "צבעוני",
      "מידות גדולות",
   ],
   sizes: ["36", "38", "40", "42"],
};
