import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import Navbar from "@/components/navigations/navbar";
import { assistant } from "@/lib/fonts";
import AdminBtn from "@/components/adminBtn";
import { auth } from "@/lib/auth";

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
   const isAdmin = await auth();
   return (
      <html lang="he" dir="rtl">
         <body
            className={`${assistant.className} h-dvh flex flex-col text-xl overflow-auto`}
         >
            <header>
               <Navbar />
            </header>
            <main className="container flex-1">{children}</main>
            {isAdmin && <AdminBtn />}
         </body>
      </html>
   );
}
